# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-27 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='isTech',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pastime',
            name='finTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pastime',
            name='illustration',
            field=models.CharField(max_length=256, null=True, verbose_name='配图'),
        ),
        migrations.AlterField(
            model_name='post',
            name='illustration',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=256),
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(max_length=32, null=True, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=128, verbose_name='标题'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
