# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 04:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0005_auto_20171006_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(null=True, to='mainsite.Tag'),
        ),
    ]
