# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-07 05:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20171007_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastime',
            name='isFin',
        ),
        migrations.AddField(
            model_name='pastime',
            name='category',
            field=models.CharField(choices=[('M', 'Movie'), ('B', 'Book'), ('G', 'Game')], default='M', max_length=1, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='pastime',
            name='view',
            field=models.CharField(default='', max_length=256, verbose_name='简评'),
        ),
    ]
